### ISSUE TITLE
GTCEu 2.2.0 compatibility 

### ISSUE THREAD

**Issue by LemADEC** [eutropius225/MultiblockTweaker#22]
Craftweaker scripts are failling when updating to GTCEu 2.2.0, probably related to some API changes:
```
[INITIALIZATION][CLIENT][ERROR] [crafttweaker]: Error executing {[98:crafttweaker]: gregtech_greenhouse.zs}: gregtech.api.recipes.Recipe.<init>(Ljava/util/List;Ljava/util/List;Ljava/util/List;Ljava/util/List;Ljava/util/List;IIZ)V
java.lang.NoSuchMethodError: gregtech.api.recipes.Recipe.<init>(Ljava/util/List;Ljava/util/List;Ljava/util/List;Ljava/util/List;Ljava/util/List;IIZ)V
	at eutros.multiblocktweaker.gregtech.recipes.CustomRecipeBuilder.build(CustomRecipeBuilder.java:39)
	at gregtech.api.recipes.RecipeBuilder.buildAndRegister(RecipeBuilder.java:577)
	at gregtech.api.recipes.crafttweaker.CTRecipeBuilder.buildAndRegister(CTRecipeBuilder.java:178)
	at Gregtech_greenhouse.__script__(gregtech_greenhouse.zs:79)
	at __ZenMain__.run(Gregtech_greenhouse)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:240)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:105)
	at youyihj.zenutils.impl.delegate.ZenUtilsTweaker.loadScript(ZenUtilsTweaker.java:47)
	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:71)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_754_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Filostorm** [comment]
There is an updated version on the [GTCEu discord](https://discord.gg/meJNk9MfSE) pinned in #crafttweaker-support

**Comment by LemADEC** [comment]
yes, the updated version is available there. Sadly, I can't publish my modpack until the update is pushed on CurseForge.

**Comment by eutro** [comment]
It's there now, I forgot to close this.
