### ISSUE TITLE
Incompatible with Gregtech 2.7.1

### ISSUE THREAD

**Issue by YiRanMushroom** [eutropius225/MultiblockTweaker#35]

**Comment by hron84** [comment]
Exception:
```
[INITIALIZATION][CLIENT][ERROR] Cannot apply Category with incompatible RecipeMap
java.lang.IllegalArgumentException
        at gregtech.api.recipes.RecipeBuilder.validate(RecipeBuilder.java:780)
        at gregtech.api.recipes.RecipeBuilder.finalizeAndValidate(RecipeBuilder.java:742)
        at eutros.multiblocktweaker.gregtech.recipes.CustomRecipeBuilder.build(CustomRecipeBuilder.java:49)
        at gregtech.api.recipes.RecipeBuilder.buildAndRegister(RecipeBuilder.java:835)
        at gregtech.integration.crafttweaker.recipe.CTRecipeBuilder.buildAndRegister(CTRecipeBuilder.java:299)
        at Vanilla.__script__(vanilla.zs:35)
        at __ZenMain__.run(Vanilla)
        at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:240)
        at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:105)
        at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:71)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_663_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
        at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:4101)
        at net.minecraft.client.main.Main.main(SourceFile:123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

script:

```
    greenhouse.recipeBuilder()
        .circuit(2)
        .notConsumable(<minecraft:sapling>)
        .inputs(<metaitem:fertilizer> * 4)
        .fluidInputs([<liquid:water> * 1000])
        .outputs(<minecraft:log> * 64)
        .outputs(<minecraft:log> * 64)
        .outputs(<minecraft:sapling>.withAmount(12))
        .duration(900)
        .EUt(60)
        .buildAndRegister();
```
